### ISSUE TITLE
Cardiology performance period 

### ISSUE THREAD

**Issue by christinakettering12345** [zkeene/scorecard#27]

**Comment by zkeene** [comment]
service line table needs a flag to tell system it is on performance period rather than quarters. need to either create a separate performance table or update the current table to have period flags for calculated metrics (e.g. Press Ganey)

Will need to develop new test cases for performance period SL and metrics

**Comment by zkeene** [comment]
Tables and CakePHP app updated with new fields. Remaining build is in actual scorecard and test cases
